apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-elasticsearch
  namespace: testingsystem
  labels:
    app: develasticsearch
    test: elasticsearch
spec:
    serviceName: elasticsearch
    replicas: 3
    selector:
        matchLabels:
            app: elasticsearch
            version: 7.4
    template:
      metadata:
          labels:
            app: elasticsearch
            version: 7.4
      spec:
        terminationGracePeriodSeconds: 1800
        serviceAccountName: dev-environment
        initContainers:
      # init-container for setting the mmap count limit
          - name: sysctl
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["sysctl", "-w", "vm.max_map_count=262144"]
        containers:
          - image: quay.io/fluentd_elasticsearch/elasticsearch:v7.4.2
            name: elasticsearch-image
            imagePullPolicy: Always
            resources:
          # need more cpu upon initialization, therefore burstable class
              limits:
                cpu: 1000m
                memory: 3Gi
              requests:
                cpu: 400m
                memory: 3Gi
            ports:
              - containerPort: 9200
                name: elasticport
                protocol: TCP
              - containerPort: 9300
                name: transport
                protocol: TCP
            livenessProbe:
              tcpSocket:
                  port: transport
                  initialDelaySeconds: 5
                  timeoutSeconds: 10
            readinessProbe:
              tcpSocket:
                  port: transport
                  initialDelaySeconds: 5
                  timeoutSeconds: 10
            volumeMounts:
              - name: elasticsearch-devvolume
                mountPath: /data
volumeClaimTemplates:
- metadata:
    name: elasticsearch-devvolume
  spec:
    accessModes: [ ReadWriteOnce ]
    resources:
     requests:
       storage: 8Gi
    storageClassName: testingstandard
    
initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
