apiVersion: v1
kind: Service
metadata:
  name: elasticsearchservice
  labels:
      app: elasticsearchservice
      kubernetes.io/cluster-service: "true"
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/name: "Elasticsearch"
spec:
    serviceAccountName: dev-environment
    ports:
      - port: 9200
        protocol: tcp
        targetport: elasticport
    selector:
        app: elasticsearch
        version: 7.4