apiVersion: v1
kind: Namespace
metadata:
  name : testingsystem
  labels:
    app: testingsystem

---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: testingsystem
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 500m
      memory: 1Gi
    type: Container

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: testingsystem
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "3"
    limits.memory: 8Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: testingsystem
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
